services:
  postgis:
    deploy:
      resources:
        limits:
          memory: 224M
    command: postgres -c shared_buffers=64MB -c max_connections=30

  redis:
    deploy:
      resources:
        limits:
          memory: 64M
    command: ["redis-server", "--save", "", "--appendonly", "no", "--maxmemory", "32mb", "--maxmemory-policy", "noeviction"]

  api:
    ports:
      - "127.0.0.1:18081:8000"
    deploy:
      resources:
        limits:
          memory: 224M

  worker:
    deploy:
      resources:
        limits:
          memory: 128M

  beat:
    deploy:
      resources:
        limits:
          memory: 48M

  web:
    ports:
      - "127.0.0.1:13000:3000"
    build:
      args:
        NEXT_PUBLIC_API_BASE_URL: "https://api.quake.jisung.lol"
    deploy:
      resources:
        limits:
          memory: 128M
